$(document).ready(function(){
	$(".person").click(function(e){
		if($(".details",$(this).parent()).is(':visible')){
			$(".details",$(this).parent()).slideUp(200);
		}else{
			$(".details",$(this).parent()).slideDown(200);	
		}
	});
});
